### ISSUE TITLE
ioBroker einbindung

### ISSUE THREAD

**Issue by Snago636** [MiGoller/xplora-api.js#2]
Hallo, gibt es eine Möglichkeit dieses in ioBroker einzubinden?

gruß Andy

**Comment by MiGoller** [comment]
Hey Andy,

Ja, gibt es, und ich bin schon dran. Dauert noch ein wenig, aber es wird. 

VG,
MiGoller

**Comment by MiGoller** [comment]
Ich werde vorab zum eigentlichen Adapter schon einmal ein Beispiel für den Script-Adapter veröffentlichen, um die Wartezeit zu versüßen. ;-)

**Comment by Snago636** [comment]
Hey cool, das klingt super. Vielen Dank. :)

**Comment by MiGoller** [comment]
So, der ioBroker Adapter ist ins Leben gerufen. Du findest den Thread unter https://forum.iobroker.net/topic/44671/neuer-adapter-xplora . Würde mich natürlich über eine positive Bewertung freuen. In dem Thread werde ich dann auch das Beispielskript veröffentlichen, wenn das für Dich in Frage kommen sollte, während der Adapter noch nicht für erste Tests zur Verfügung steht.

**Comment by MiGoller** [comment]
Hey. 

Du findest die Doku unter https://github.com/MiGoller/xplora-api.js/blob/main/examples/iobroker/README.md . Laut ioBroker Forum hilft Dir das auch schon weiter. 

Ich würde mich natürlich auch über eine positive Bewertung im Forum oder einen Stern hier im Repository freuen. ;-)

VG, MiGoller
